<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2854" started-at="2018-12-12T21:15:15Z" finished-at="2018-12-12T21:15:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2854" started-at="2018-12-12T21:15:15Z" finished-at="2018-12-12T21:15:18Z">
      <class name="pomdesign.WebOrderTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:pomdesign.WebOrderTest@27efef64]" name="setUp" is-config="true" duration-ms="2175" started-at="2018-12-12T21:15:15Z" finished-at="2018-12-12T21:15:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ProductTest()[pri:0, instance:pomdesign.WebOrderTest@27efef64]" name="ProductTest" duration-ms="584" started-at="2018-12-12T21:15:17Z" finished-at="2018-12-12T21:15:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$1000] but found [$100]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$1000] but found [$100]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pomdesign.WebOrderTest.ProductTest(WebOrderTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductTest -->
        <test-method status="PASS" signature="closeUp()[pri:0, instance:pomdesign.WebOrderTest@27efef64]" name="closeUp" is-config="true" duration-ms="77" started-at="2018-12-12T21:15:18Z" finished-at="2018-12-12T21:15:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- pomdesign.WebOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
